Add Revolver Ability & Polish a few things
The-GameDJs/CostumeCurse pull request #132
Opened 2021-02-07 22:17 UTC by armandorusso

- Added Ganiel's Revolver Ability! Drag in bullets and shoot down Pimpkin heads!
See the Gif Below!

Polish Adjustments I did while adding the ability:
- Fixed URP settings to improve anti-alliasing and shadows. Game looks a lot smoother now!
- Adjusted the damage of Confection. It was too powerful for the difficulty and cost
- Fixed the Confection Animation. It now plays at the end of the ability (just like how Revolver is)

2021-02-07 22:25 UTC, George540 approved these changes
Looks good! Good teamwork. Animation and some delays may be changed later in the debug phase. I made an issue about it for later.

2021-02-08 02:50 UTC, eli-lam requested changes
Good job on the ability! Just a small change needed

2021-02-08 02:50 UTC, eli-lam commented on Assets/Scripts/Combat/Abilities/PimpkinHead.cs
> +    private float randomIntX;
Pascal case!

2021-02-08 02:57 UTC, armandorusso commented on Assets/Scripts/Combat/Abilities/PimpkinHead.cs
> +    private float randomIntX;
Fixed!

2021-02-08 02:58 UTC, eli-lam approved these changes
LGTM!

2021-02-08 02:58 UTC, merged