Dialogue overworld
The-GameDJs/CostumeCurse pull request #81
Opened 2020-12-08 23:47 UTC by Lerihan

- Placed NPCs around the shared main scene

- Changed Prefabs (Ghosts, tombstones) to include "InteractiveNPC" script

- Added dialogue to all NPCs (Some tombstones are missing dialogue, feel free to add)

- Small bug with the position of the "OtherNPC" bubble

2020-12-09 18:35 UTC, danielwiktorczyk requested changes
I updated most of the convos, but there still remains ones that haven't been updated

2020-12-10 05:18 UTC, armandorusso approved these changes
Looks good! Love the dialogue, it's quirky and funny I love it. Just a small spelling fix: for some of the dialogue, wherever there's either a question mark or an exclamation point, remove the space before it (ex: "where ? hello !").

2020-12-10 17:58 UTC, danielwiktorczyk commented
Perhaps Bias cuz I helped you after, but I think it looks all good now! Great job with the convos!! Really fun :)

2020-12-10 17:58 UTC, danielwiktorczyk approved these changes

2020-12-10 18:15 UTC, merged